export { default as absolute_url } from "@11ty/eleventy-plugin-rss/src/absoluteUrl.js";
export { color } from "./color.js";
export { excludes } from "./excludes.js";
export { hostname } from "./hostname.js";
export { includes } from "./includes.js";
export { itinerary } from "./itinerary.js";
export { markdown } from "./markdown.js";
export { pluralise } from "./pluralise.js";
export { publication } from "./publication.js";
export { syndication_target } from "./syndication-target.js";
export { template_content_to_feed_html } from "./template-content-to-feed-html.js";
