export const places = [
  {
    name: "Aberdeen (ABD)",
    address: { locality: "Aberdeen", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 57.143_687, longitude: -2.098_812 },
  },
  {
    name: "Ålesund",
    address: { locality: "Ålesund", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.469_563, longitude: 6.152_188 },
  },
  {
    name: "Amara Donostia",
    address: { locality: "Donostia-San Sebastián", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 43.313_188, longitude: -1.981_687 },
  },
  {
    name: "Amsterdam Airport Schiphol (AMS)",
    uid: "https://schiphol.nl",
    address: { locality: "Amsterdam", countryName: "Netherlands" },
    category: ["airport"],
    geo: { latitude: 52.310_563, longitude: 4.768_313 },
  },
  {
    name: "Amsterdam Amstel",
    address: { locality: "Amsterdam", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 52.346_688, longitude: 4.918_313 },
  },
  {
    name: "Amsterdam Centraal",
    address: { locality: "Amsterdam", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 52.379_188, longitude: 4.900_313 },
  },
  {
    name: "Angmering (ANG)",
    address: { locality: "East Preston", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.816_389, longitude: -0.489_167 },
  },
  {
    name: "Antwerpen-Centraal",
    address: { locality: "Antwerp", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 51.217_187, longitude: 4.421_438 },
  },
  {
    name: "Ashford International (AFK)",
    address: { locality: "Ashford", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.143_687, longitude: 0.876_313 },
  },
  {
    name: "Auckland Airport (AKL)",
    uid: "https://aucklandairport.co.nz",
    address: { locality: "Auckland", countryName: "New Zealand" },
    category: ["airport"],
    geo: { latitude: -37.008_187, longitude: 174.785_063 },
  },
  {
    name: "Augsburg",
    address: { locality: "Augsburg", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.365_556, longitude: 10.886_389 },
  },
  {
    name: "Austin-Bergstrom International Airport (AUS)",
    uid: "https://austintexas.gov/airport",
    address: { locality: "Austin", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 30.197_438, longitude: -97.666_313 },
  },
  {
    name: "Åndalsnes",
    address: { locality: "Åndalsnes", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.567_563, longitude: 7.694_312 },
  },
  {
    name: "Bahnhof Basel SBB",
    address: { locality: "Basel", countryName: "Switzerland" },
    category: ["station"],
    geo: { latitude: 47.547_563, longitude: 7.589_688 },
  },
  {
    name: "Barcelona França",
    address: { locality: "Barcelona", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 41.383_938, longitude: 2.186_438 },
  },
  {
    name: "Barcelona Sants",
    address: { locality: "Barcelona", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 41.378_938, longitude: 2.139_938 },
  },
  {
    name: "Barnham (BAA)",
    address: { locality: "Barnham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.830_938, longitude: -0.640_062 },
  },
  {
    name: "Bath Spa (BTH)",
    address: { locality: "Bath", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.377_688, longitude: -2.356_938 },
  },
  {
    name: "Belfast International Airport (BFS)",
    uid: "https://belfastairport.com",
    address: { locality: "Belfast", countryName: "Northern Ireland" },
    category: ["airport"],
    geo: { latitude: 54.656_313, longitude: -6.217_187 },
  },
  {
    name: "Belfast Lanyon Place",
    address: { locality: "Belfast", countryName: "Northern Ireland" },
    category: ["station"],
    geo: { latitude: 54.595_188, longitude: -5.917_187 },
  },
  {
    name: "Berlin",
    address: { locality: "Berlin", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 52.525_063, longitude: 13.369_438 },
  },
  {
    name: "Berlin Schönefeld Airport (SXF)",
    uid: "https://berlin-airport.de/en",
    address: { locality: "Berlin", countryName: "Germany" },
    category: ["airport"],
    geo: { latitude: 52.373_313, longitude: 13.506_438 },
  },
  {
    name: "Birmingham Airport (BHX)",
    uid: "https://birminghamairport.co.uk",
    address: { locality: "Birmingham", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 52.452_438, longitude: -1.743_562 },
  },
  {
    name: "Birmingham Moor Street (BMO)",
    address: { locality: "Birmingham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.478_938, longitude: -1.892_562 },
  },
  {
    name: "Birmingham New Street (BHM)",
    address: { locality: "Birmingham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.477_812, longitude: -1.898_937 },
  },
  {
    name: "Blackfriars (BFR)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.5116, longitude: -0.103 },
  },
  {
    name: "Bloxwich North (BWN)",
    address: { locality: "Walsall", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.625_313, longitude: -2.017_687 },
  },
  {
    name: "Bournemouth (BMH)",
    address: { locality: "Bournemouth", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.728, longitude: -1.864 },
  },
  {
    name: "Brasília–Presidente Juscelino Kubitschek International Airport (BSB)",
    uid: "https://www.bsb.aero/br/",
    address: { locality: "Brasília", countryName: "Brazil" },
    category: ["airport"],
    geo: { latitude: -15.869_688, longitude: -47.917_187 },
  },
  {
    name: "Brighton (BTN)",
    address: { locality: "Brighton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.828_813, longitude: -0.140_938 },
  },
  {
    name: "Bristol Temple Meads (BRI)",
    address: { locality: "Bristol", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.449_688, longitude: -2.581_062 },
  },
  {
    name: "Britomart Transport Centre",
    address: { locality: "Auckland", countryName: "New Zealand" },
    category: ["station"],
    geo: { latitude: -36.844_188, longitude: 174.767_812 },
  },
  {
    name: "Bruges",
    address: { locality: "Bruges", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 51.197_688, longitude: 3.217_813 },
  },
  {
    name: "Brussels-South",
    address: { locality: "Brussels", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 50.836_063, longitude: 4.335_438 },
  },
  {
    name: "Budapest Keleti",
    address: { locality: "Budapest", countryName: "Hungary" },
    category: ["station"],
    geo: { latitude: 47.500_438, longitude: 19.083_938 },
  },
  {
    name: "Cabis Bay (CBB)",
    address: { locality: "St Ives", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.197_063, longitude: -5.464_062 },
  },
  {
    name: "Caesars Palace Hotel & Casino",
    address: { locality: "Las Vegas", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 36.116_173, longitude: -115.176_69 },
  },
  {
    name: "Cairns International Airport (CNS)",
    uid: "https://cairnsairport.com.au",
    address: { locality: "Cairns", countryName: "Australia" },
    category: ["airport"],
    geo: { latitude: -16.877_813, longitude: 145.749_937 },
  },
  {
    name: "Cambridge (CBG)",
    address: { locality: "Cambridge", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.194_187, longitude: 0.137_438 },
  },
  {
    name: "Cardiff Central (CDF)",
    address: { locality: "Cardiff", countryName: "Wales" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.476_188, longitude: -3.179_062 },
  },
  {
    name: "Carlisle (CAR)",
    address: { locality: "Carlisle", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 54.890_688, longitude: -2.933_188 },
  },
  {
    name: "Chester (CTR)",
    address: { locality: "Chester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.196_562, longitude: -2.880_187 },
  },
  {
    name: "Chicago Midway International Airport (MDW)",
    uid: "https://flychicago.com/midway",
    address: { locality: "Chicago", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 41.786_812, longitude: -87.752_188 },
  },
  {
    name: "Chorley (CRL)",
    address: { locality: "Chorley", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.652_563, longitude: -2.626_937 },
  },
  {
    name: "Clapham Junction (CLJ)",
    address: { locality: "Clapham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.465_187, longitude: -0.170_812 },
  },
  {
    name: "Como San Giovanni",
    address: { locality: "Como", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.808_889, longitude: 9.072_306 },
  },
  {
    name: "Copenhagen Airport, Kastrup (CPH)",
    uid: "https://cph.dk/en",
    address: { locality: "Kastrup", countryName: "Denmark" },
    category: ["airport"],
    geo: { latitude: 55.618_063, longitude: 12.650_813 },
  },
  {
    name: "Copenhagen Central",
    address: { locality: "Copenhagen", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 55.672_813, longitude: 12.564_938 },
  },
  {
    name: "Craignure Mull Ferry Terminal",
    address: { locality: "Craignure", countryName: "Scotland" },
    category: ["port"],
    geo: { latitude: 56.470_688, longitude: -5.706_312 },
  },
  {
    name: "Crewe (CRE)",
    address: { locality: "Crewe", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.089_563, longitude: -2.433_562 },
  },
  {
    name: "Dallas/Fort Worth International Airport (DFW)",
    uid: "https://dfwairport.com",
    address: { locality: "Dallas", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 32.899_812, longitude: -97.040_312 },
  },
  {
    name: "Den Haag Centraal",
    address: { locality: "The Hague", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 52.080_563, longitude: 4.325_813 },
  },
  {
    name: "Derby (DBY)",
    address: { locality: "Derby", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.916_188, longitude: -1.463_313 },
  },
  {
    name: "Dieppe",
    address: { locality: "Dieppe", countryName: "France" },
    category: ["station"],
    geo: { latitude: 49.921_438, longitude: 1.081_063 },
  },
  {
    name: "Doncaster (DON)",
    address: { locality: "Doncaster", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.5225, longitude: -1.1395 },
  },
  {
    name: "Düsseldorf",
    address: { locality: "Düsseldorf", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 51.220_278, longitude: 6.792_778 },
  },
  {
    name: "Dubai International Airport (DXB)",
    uid: "https://dubaiairports.ae",
    address: { locality: "Dubai", countryName: "United Arab Emirates" },
    category: ["airport"],
    geo: { latitude: 25.253_187, longitude: 55.365_688 },
  },
  {
    name: "Dublin Airport (DUB)",
    uid: "https://dublinairport.com",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["airport"],
    geo: { latitude: 53.426_438, longitude: -6.249_937 },
  },
  {
    name: "Dublin Connolly",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["station"],
    geo: { latitude: 53.350_938, longitude: -6.249_937 },
  },
  {
    name: "Dublin Heuston",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["station"],
    geo: { latitude: 53.346_313, longitude: -6.294_187 },
  },
  {
    name: "Dublin Port",
    uid: "https://dublinport.ie",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["port"],
    geo: { latitude: 53.345_063, longitude: -6.196_187 },
  },
  {
    name: "Dundee (DEE)",
    address: { locality: "Dundee", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.457_687, longitude: -2.969_437 },
  },
  {
    name: "Edinburgh Waverley (EDB)",
    address: { locality: "Edinburgh", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.951_938, longitude: -3.189_937 },
  },
  {
    name: "Emeryville",
    address: { locality: "Emeryville", countryName: "United States" },
    category: ["station"],
    geo: { latitude: 37.840_438, longitude: -122.291_812 },
  },
  {
    name: "Exeter St David’s (EXD)",
    address: { locality: "Exeter", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.729_312, longitude: -3.543_563 },
  },
  {
    name: "Fareham (FRM)",
    address: { locality: "Fareham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.852_934, longitude: -1.191_898 },
  },
  {
    name: "Farringdon (ZFD)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.520_556, longitude: -0.105 },
  },
  {
    name: "Florence Santa Maria Novella",
    address: { locality: "Florence", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 43.776_438, longitude: 11.247_813 },
  },
  {
    name: "Flåm",
    address: { locality: "Flåm", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 60.863_687, longitude: 7.118_938 },
  },
  {
    name: "Frankfurt Airport (FRA)",
    uid: "https://frankfurt-airport.com",
    address: { locality: "Frankfurt am Main", countryName: "Germany" },
    category: ["airport"],
    geo: { latitude: 50.037_937, longitude: 8.562_188 },
  },
  {
    name: "Frankfurt (Main)",
    address: { locality: "Frankfurt am Main", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 50.106_944, longitude: 8.6625 },
  },
  {
    name: "Fredericia",
    address: { locality: "Fredericia", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 55.568_188, longitude: 9.740_437 },
  },
  {
    name: "Freiburg",
    address: { locality: "Freiburg im Breisgau", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 47.996_562, longitude: 7.840_438 },
  },
  {
    name: "Füssen",
    address: { locality: "Füssen", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 47.570_263, longitude: 10.697_818 },
  },
  {
    name: "Galway",
    address: { locality: "Galway", countryName: "Ireland" },
    category: ["station"],
    geo: { latitude: 53.273_563, longitude: -9.047_063 },
  },
  {
    name: "Gatwick (GTW)",
    address: { locality: "Gatwick Airport", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.156_688, longitude: -0.161_187 },
  },
  {
    name: "Gatwick Airport (LGW)",
    uid: "https://gatwickairport.com",
    address: { locality: "Gatwick", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 51.153_688, longitude: -0.182_062 },
  },
  {
    name: "Geiranger",
    address: { locality: "Geiranger", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.102_188, longitude: 7.204_813 },
  },
  {
    name: "Glasgow Central (GLC)",
    address: { locality: "Glasgow", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.859_062, longitude: -4.258_062 },
  },
  {
    name: "Glasgow Queen Street (GLQ)",
    address: { locality: "Glasgow", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.862_437, longitude: -4.251_187 },
  },
  {
    name: "Gothenburg Central",
    address: { locality: "Gothenburg", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 57.708_562, longitude: 11.973_313 },
  },
  {
    name: "Greenwich (GNW)",
    address: { locality: "Greenwich", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.478_062, longitude: -0.013_188 },
  },
  {
    name: "Guernsey Ferry Port",
    address: { locality: "St. Peter Port", countryName: "Guernsey" },
    category: ["port"],
    geo: { latitude: 49.457_313, longitude: -2.529_062 },
  },
  {
    name: "Hamburg",
    address: { locality: "Hamburg", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 53.552_938, longitude: 10.006_563 },
  },
  {
    name: "Hartsfield-Jackson Atlanta International Airport (ATL)",
    uid: "https://atl.com",
    address: { locality: "Atlanta", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 33.640_687, longitude: -84.427_688 },
  },
  {
    name: "Hässleholm Central",
    address: { locality: "Hässleholm", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 56.157_813, longitude: 13.763_188 },
  },
  {
    name: "Hastings (HGS)",
    address: { locality: "Hastings", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.857_937, longitude: 0.576_813 },
  },
  {
    name: "Haugesund",
    address: { locality: "Haugesund", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 59.411_063, longitude: 5.257_313 },
  },
  {
    name: "Havant (HAV)",
    address: { locality: "Havant", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.854_312, longitude: -0.981_562 },
  },
  {
    name: "Hellesylt",
    address: { locality: "Hellesylt", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.085_563, longitude: 6.873_938 },
  },
  {
    name: "Hendaye",
    address: { locality: "Hendaye", countryName: "France" },
    category: ["station"],
    geo: { latitude: 43.353_062, longitude: -1.781_812 },
  },
  {
    name: "Hilton Santa Monica Hotel & Suites",
    address: { locality: "Santa Monica", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 34.011_73, longitude: -118.491_17 },
  },
  {
    name: "Holiday Inn Express & Suites Albuquerque Historic Old Town",
    address: { locality: "Albuquerque", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 35.108_66, longitude: -106.660_46 },
  },
  {
    name: "Holyhead (HHD)",
    address: { locality: "Holyhead", countryName: "Wales" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.307_688, longitude: -4.631_062 },
  },
  {
    name: "Hove (HOV)",
    address: { locality: "Hove", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.835_063, longitude: -0.171_062 },
  },
  {
    name: "Hyatt Regency",
    address: { locality: "Austin", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 30.260_57, longitude: -97.747_21 },
  },
  {
    name: "Innsbruck",
    address: { locality: "Innsbruck", countryName: "Austria" },
    category: ["station"],
    geo: { latitude: 47.263_313, longitude: 11.400_938 },
  },
  {
    name: "Inverness (INV)",
    address: { locality: "Inverness", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 57.48, longitude: -4.223 },
  },
  {
    name: "John F. Kennedy International Airport (JFK)",
    uid: "https://jfkairport.com",
    address: { locality: "New York", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 40.641_312, longitude: -73.778_188 },
  },
  {
    name: "Keflavík International Airport (KEF)",
    uid: "https://www.isavia.is/en/keflavik-airport",
    address: { locality: "Keflavík", countryName: "Iceland" },
    category: ["airport"],
    geo: { latitude: 63.978_563, longitude: -22.635_063 },
  },
  {
    name: "King Street Station",
    address: { locality: "Seattle", countryName: "United States" },
    category: ["station"],
    geo: { latitude: 47.598_438, longitude: -122.329_937 },
  },
  {
    name: "Köln",
    address: { locality: "Cologne", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 50.943_188, longitude: 6.958_562 },
  },
  {
    name: "Le Havre",
    address: { locality: "Le Harve", countryName: "France" },
    category: ["station"],
    geo: { latitude: 49.492_687, longitude: 0.124_813 },
  },
  {
    name: "Leeds (LDS)",
    address: { locality: "Leeds", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.794, longitude: -1.547 },
  },
  {
    name: "Leicester (LEI)",
    address: { locality: "Leicester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.631_188, longitude: -1.125_187 },
  },
  {
    name: "Lewes (LWS)",
    address: { locality: "Lewes", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.870_563, longitude: 0.011_437 },
  },
  {
    name: "Lille-Europe",
    address: { locality: "Lille", countryName: "France" },
    category: ["station"],
    geo: { latitude: 50.639_062, longitude: 3.075_688 },
  },
  {
    name: "Lisbon Orient",
    address: { locality: "Lisbon", countryName: "Portugal" },
    category: ["station"],
    geo: { latitude: 38.767_813, longitude: -9.099_312 },
  },
  {
    name: "Lisbon Portela Airport (LIS)",
    uid: "https://www.ana.pt/en/lis/home",
    address: { locality: "Lisbon", countryName: "Portugal" },
    category: ["airport"],
    geo: { latitude: 38.775_563, longitude: -9.135_312 },
  },
  {
    name: "Littlehampton (LIT)",
    address: { locality: "Littlehampton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.810_063, longitude: -0.545_938 },
  },
  {
    name: "Liverpool Lime Street (LIV)",
    address: { locality: "Liverpool", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.407_563, longitude: -2.977_312 },
  },
  {
    name: "Liège-Guillemins",
    address: { locality: "Liège", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 50.624_438, longitude: 5.566_688 },
  },
  {
    name: "London Bridge (LBG)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.504_312, longitude: -0.084_812 },
  },
  {
    name: "London Euston (EUS)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.528_063, longitude: -0.133_188 },
  },
  {
    name: "London Heathrow Airport (LHR)",
    uid: "https://heathrow.com",
    address: { locality: "London", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 51.470_063, longitude: -0.454_312 },
  },
  {
    name: "London King’s Cross (KGX)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.532_063, longitude: -0.123_312 },
  },
  {
    name: "London Luton Airport (LTN)",
    uid: "https://www.london-luton.co.uk",
    address: { locality: "Luton", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 51.876_313, longitude: -0.371_687 },
  },
  {
    name: "London Marylebone (MYB)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.522_438, longitude: -0.163_187 },
  },
  {
    name: "London Paddington (PAD)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.516_687, longitude: -0.176_937 },
  },
  {
    name: "London St Pancras International (STP)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.531_438, longitude: -0.126_187 },
  },
  {
    name: "London Victoria (VIC)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.495_187, longitude: -0.143_937 },
  },
  {
    name: "Los Angeles International Airport (LAX)",
    uid: "https://flylax.com",
    address: { locality: "Los Angeles", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 33.941_563, longitude: -118.408_563 },
  },
  {
    name: "Lucerne",
    address: { locality: "Lucerne", countryName: "Switzerland" },
    category: ["station"],
    geo: { latitude: 47.050_438, longitude: 8.310_313 },
  },
  {
    name: "Lyon-Part-Dieu",
    address: { locality: "Lyon", countryName: "France" },
    category: ["station"],
    geo: { latitude: 45.760_556, longitude: 4.859_444 },
  },
  {
    name: "Maastricht",
    address: { locality: "Maastricht", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 50.849_688, longitude: 5.705_312 },
  },
  {
    name: "Madrid Atocha",
    address: { locality: "Madrid", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 40.405_063, longitude: -3.688_312 },
  },
  {
    name: "Madrid Chamartín",
    address: { locality: "Madrid", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 40.471_938, longitude: -3.682_562 },
  },
  {
    name: "Malmö Central",
    address: { locality: "Malmö", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 55.609_062, longitude: 12.999_938 },
  },
  {
    name: "Manchester Piccadilly (MAN)",
    address: { locality: "Manchester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.477_438, longitude: -2.231_187 },
  },
  {
    name: "Manchester Victoria (MCV)",
    address: { locality: "Manchester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.487_562, longitude: -2.242_188 },
  },
  {
    name: "Margate (MAR)",
    address: { locality: "Margate", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.385_437, longitude: 1.372_313 },
  },
  {
    name: "McCarran International Airport (LAS)",
    uid: "https://mccarran.com",
    address: { locality: "Las Vegas", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 36.083_937, longitude: -115.153_688 },
  },
  {
    name: "Melbourne Airport (MEL)",
    uid: "https://www.melbourneairport.com.au",
    address: { locality: "Melbourne", countryName: "Australia" },
    category: ["airport"],
    geo: { latitude: -37.669_063, longitude: 144.841_063 },
  },
  {
    name: "Milano Centrale",
    address: { locality: "Milan", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.486_111, longitude: 9.203_611 },
  },
  {
    name: "Milton Keynes Central (MKC)",
    address: { locality: "Milton Keynes", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.034_438, longitude: -0.773_812 },
  },
  {
    name: "Montréal–Trudeau International Airport (YUL)",
    uid: "https://admtl.com",
    address: { locality: "Montréal", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 45.465_688, longitude: -73.745_438 },
  },
  {
    name: "Munich International Airport (MUC)",
    uid: "https://munich-airport.com",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["airport"],
    geo: { latitude: 48.353_688, longitude: 11.775_063 },
  },
  {
    name: "Munich",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.140_833, longitude: 11.555 },
  },
  {
    name: "Munich East",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.126_944, longitude: 11.604_722 },
  },
  {
    name: "Munich Pasing",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.150_063, longitude: 11.461_562 },
  },
  {
    name: "Newark Liberty International Airport (EWR)",
    uid: "https://newarkairport.com",
    address: { locality: "Newark", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 40.689_563, longitude: -74.174_437 },
  },
  {
    name: "Newark Northgate (NNG)",
    address: { locality: "Newark-on-Trent", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.081, longitude: -0.799 },
  },
  {
    name: "Newcastle (NCL)",
    address: { locality: "Newcastle", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 54.968_438, longitude: -1.617_063 },
  },
  {
    name: "Newhaven Harbour (NVH)",
    address: { locality: "Newhaven", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.789_688, longitude: 0.055_313 },
  },
  {
    name: "Newport (NWP)",
    address: { locality: "Newport", countryName: "Wales" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.588_688, longitude: -3.001_187 },
  },
  {
    name: "Newquay (NQY)",
    address: { locality: "Newquay", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.415_063, longitude: -5.075_687 },
  },
  {
    name: "Nice-Ville",
    address: { locality: "Nice", countryName: "France" },
    category: ["station"],
    geo: { latitude: 43.704_312, longitude: 7.261_938 },
  },
  {
    name: "Norman Y. Mineta San Jose International Airport (SJC)",
    uid: "https://flysanjose.com",
    address: { locality: "San Jose", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 37.363_937, longitude: -121.928_938 },
  },
  {
    name: "Norwich (NRW)",
    address: { locality: "Norwich", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.626_938, longitude: 1.306_563 },
  },
  {
    name: "Nottingham (NOT)",
    address: { locality: "Nottingham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.947_063, longitude: -1.146_812 },
  },
  {
    name: "Nürnberg",
    address: { locality: "Nürnberg", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 49.446_389, longitude: 11.081_944 },
  },
  {
    name: "Oban (OBN)",
    address: { locality: "Oban", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.412_563, longitude: -5.473_937 },
  },
  {
    name: "Oban Ferry Terminal",
    address: { locality: "Oban", countryName: "Scotland" },
    category: ["port"],
    geo: { latitude: 56.412_188, longitude: -5.476_062 },
  },
  {
    name: "Olden",
    address: { locality: "Olden", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 61.842_688, longitude: 6.810_688 },
  },
  {
    name: "Oslo Central",
    address: { locality: "Oslo", countryName: "Norway" },
    category: ["station"],
    geo: { latitude: 59.911_063, longitude: 10.752_438 },
  },
  {
    name: "Ottawa International Airport (YOW)",
    uid: "https://yow.ca/en",
    address: { locality: "Ottawa", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 45.319_188, longitude: -75.669_188 },
  },
  {
    name: "Ottawa Train Station",
    address: { locality: "Ottawa", countryName: "Canada" },
    category: ["station"],
    geo: { latitude: 45.416_438, longitude: -75.651_688 },
  },
  {
    name: "O’Hare International Airport (ORD)",
    uid: "https://flychicago.com/ohare",
    address: { locality: "Chicago", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 41.974_187, longitude: -87.907_313 },
  },
  {
    name: "Pacific Central Station",
    address: { locality: "Vancouver", countryName: "Canada" },
    category: ["station"],
    geo: { latitude: 49.273_688, longitude: -123.097_938 },
  },
  {
    name: "Par (PAR)",
    address: { locality: "Par", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.355_938, longitude: -4.704_438 },
  },
  {
    name: "Paris-Austerlitz",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.841_813, longitude: 2.366_062 },
  },
  {
    name: "Paris-Est",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.876_812, longitude: 2.359_312 },
  },
  {
    name: "Paris-Gare-de-Lyon",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.844_313, longitude: 2.374_438 },
  },
  {
    name: "Paris-Montparnasse",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.841_188, longitude: 2.320_563 },
  },
  {
    name: "Paris-Nord",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.880_938, longitude: 2.355_312 },
  },
  {
    name: "Penzance (PNZ)",
    address: { locality: "Penzance", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.121_688, longitude: -5.532_563 },
  },
  {
    name: "Petersfield (PTR)",
    address: { locality: "Petersfield", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.007, longitude: -0.941 },
  },
  {
    name: "Phoenix Sky Harbor International Airport (PHX)",
    uid: "https://skyharbor.com",
    address: { locality: "Phoenix", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 33.437_313, longitude: -112.007_812 },
  },
  {
    name: "Picton",
    address: { locality: "Picton Ferry Terminal", countryName: "New Zealand" },
    category: ["port"],
    geo: { latitude: -41.285_312, longitude: 174.005_313 },
  },
  {
    name: "Poole Ferry Terminal",
    address: { locality: "Poole", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.708_062, longitude: -1.995_437 },
  },
  {
    name: "Port of Dieppe",
    address: { locality: "Dieppe", countryName: "France" },
    category: ["port"],
    geo: { latitude: 49.933_688, longitude: 1.088_063 },
  },
  {
    name: "Port of Holyhead",
    uid: "https://holyheadport.co.uk",
    address: { locality: "Holyhead", countryName: "Wales" },
    category: ["port"],
    geo: { latitude: 53.309_313, longitude: -4.628_937 },
  },
  {
    name: "Port of Newhaven",
    uid: "https://newhavenport.com",
    address: { locality: "Newhaven", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.790_312, longitude: 0.054_688 },
  },
  {
    name: "Port of Strevanger",
    address: { locality: "Strevanger", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 58.972_563, longitude: 5.729_813 },
  },
  {
    name: "Portland International Airport (PDX)",
    uid: "https://flypdx.com",
    address: { locality: "Portland", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 45.591_313, longitude: -122.592_313 },
  },
  {
    name: "Porto Campanha",
    address: { locality: "Porto", countryName: "Portugal" },
    category: ["station"],
    geo: { latitude: 41.148_813, longitude: -8.585_437 },
  },
  {
    name: "Portsmouth Harbour (PMH)",
    address: { locality: "Portsmouth", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.797_188, longitude: -1.107_563 },
  },
  {
    name: "Portsmouth Harbour Station Pier",
    address: { locality: "Portsmouth", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.797_063, longitude: -1.109_312 },
  },
  {
    name: "Prague",
    address: { locality: "Prague", countryName: "Czechia" },
    category: ["station"],
    geo: { latitude: 50.083_188, longitude: 14.435_313 },
  },
  {
    name: "Preston (PRE)",
    address: { locality: "Preston", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.755_313, longitude: -2.707_188 },
  },
  {
    name: "Preston Park (PRP)",
    address: { locality: "Brighton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.845_938, longitude: -0.155_062 },
  },
  {
    name: "Puttgarden",
    address: { locality: "Puttgarden", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 54.500_938, longitude: 11.226_188 },
  },
  {
    name: "Puttgarden",
    address: { locality: "Puttgarden", countryName: "Germany" },
    category: ["port"],
    geo: { latitude: 54.502_813, longitude: 11.228_688 },
  },
  {
    name: "Reading (RDG)",
    address: { locality: "Reading", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.458_313, longitude: -0.971_437 },
  },
  {
    name: "Roma Termini",
    address: { locality: "Rome", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 41.901_063, longitude: 12.501_188 },
  },
  {
    name: "Rome Ciampino Giovan Battista Pastine Airport (CIA)",
    uid: "https://adr.it/ciampino",
    address: { locality: "Rome", countryName: "Italy" },
    category: ["airport"],
    geo: { latitude: 41.799_188, longitude: 12.592_813 },
  },
  {
    name: "Rotterdam Centraal",
    address: { locality: "Rotterdam", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 51.924_313, longitude: 4.470_063 },
  },
  {
    name: "Rouen-Rive-Droite",
    address: { locality: "Rouen", countryName: "France" },
    category: ["station"],
    geo: { latitude: 49.448_813, longitude: 1.094_188 },
  },
  {
    name: "Ryde Pier Head (RYP)",
    address: { locality: "Ryde", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.739_187, longitude: -1.160_062 },
  },
  {
    name: "Ryde Pier Head",
    address: { locality: "Ryde", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.739_438, longitude: -1.160_562 },
  },
  {
    name: "Rødby Færge",
    address: { locality: "Rødby", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 54.655_188, longitude: 11.354_813 },
  },
  {
    name: "Rødbyhavn",
    address: { locality: "Rødby", countryName: "Denmark" },
    category: ["port"],
    geo: { latitude: 54.654_688, longitude: 11.351_438 },
  },
  {
    name: "San Francisco International Airport (SFO)",
    uid: "https://flysfo.com",
    address: { locality: "San Francisco", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 37.621_312, longitude: -122.378_938 },
  },
  {
    name: "San Sebastián",
    address: { locality: "Donostia-San Sebastián", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 43.316_188, longitude: -1.977_437 },
  },
  {
    name: "Seattle-Tacoma International Airport (SEA)",
    uid: "http://flysea.org",
    address: { locality: "SeaTac", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 47.450_187, longitude: -122.308_813 },
  },
  {
    name: "Shanklin (SHN)",
    address: { locality: "Shanklin", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.633_813, longitude: -1.179_937 },
  },
  {
    name: "Sheffield (SHF)",
    address: { locality: "Sheffield", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.378_313, longitude: -1.462_937 },
  },
  {
    name: "Southampton Airport Parkway (SOA)",
    address: { locality: "Southampton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.950_813, longitude: -1.363_062 },
  },
  {
    name: "Southampton Central (SOU)",
    address: { locality: "Southampton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.908, longitude: -1.414 },
  },
  {
    name: "Southampton Cruise Terminal",
    uid: "http://southamptonvts.co.uk",
    address: { locality: "Southampton", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.893_563, longitude: -1.400_062 },
  },
  {
    name: "St Erth (SER)",
    address: { locality: "St Erth", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.170_563, longitude: -5.444_312 },
  },
  {
    name: "St Ives (SIV)",
    address: { locality: "St Ives", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.208_937, longitude: -5.477_937 },
  },
  {
    name: "Stirling (STG)",
    address: { locality: "Stirling", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.119_813, longitude: -3.935_437 },
  },
  {
    name: "Stockholm Central",
    address: { locality: "Stockholm", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 59.330_063, longitude: 18.058_313 },
  },
  {
    name: "Strasbourg-Ville",
    address: { locality: "Strasbourg", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.585_063, longitude: 7.734_438 },
  },
  {
    name: "Stuttgart",
    address: { locality: "Stuttgart", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.783_889, longitude: 9.181_667 },
  },
  {
    name: "Suvarnabhumi Airport (BKK)",
    uid: "https://suvarnabhumi.airportthai.co.th",
    address: { locality: "Bang Phli", countryName: "Thailand" },
    category: ["airport"],
    geo: { latitude: 13.689_937, longitude: 100.750_063 },
  },
  {
    name: "Sydney Airport (SYD)",
    uid: "https://sydneyairport.com.au",
    address: { locality: "Sydney", countryName: "Australia" },
    category: ["airport"],
    geo: { latitude: -33.939_938, longitude: 151.175_312 },
  },
  {
    name: "São Paulo-Guarulhos International Airport (GRU)",
    uid: "https://www.gru.com.br/en",
    address: { locality: "Guarulhos", countryName: "Brazil" },
    category: ["airport"],
    geo: { latitude: -23.430_563, longitude: -46.473_062 },
  },
  {
    name: "The Mosser",
    address: { locality: "San Francisco", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 37.785_084, longitude: -122.405_006 },
  },
  {
    name: "Three Bridges (TBD)",
    address: { locality: "Three Bridges", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.118_063, longitude: -0.161_687 },
  },
  {
    name: "Torino Porta Susa",
    address: { locality: "Turin", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.0725, longitude: 7.665_833 },
  },
  {
    name: "Toronto Pearson International Airport (YYZ)",
    uid: "https://torontopearson.com/en",
    address: { locality: "Toronto", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 43.677_688, longitude: -79.624_813 },
  },
  {
    name: "Toronto Union Station",
    address: { locality: "Toronto", countryName: "Canada" },
    category: ["station"],
    geo: { latitude: 43.645_187, longitude: -79.380_688 },
  },
  {
    name: "Trondheim",
    address: { locality: "Trondheim", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 63.438_313, longitude: 10.397_063 },
  },
  {
    name: "Truro (TRU)",
    address: { locality: "Truro", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.264_062, longitude: -5.064_187 },
  },
  {
    name: "Union Station",
    address: { locality: "Chicago", countryName: "United States" },
    category: ["station"],
    geo: { latitude: 41.878_688, longitude: -87.640_438 },
  },
  {
    name: "Utrecht Centraal",
    address: { locality: "Utrecht", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 52.089_438, longitude: 5.109_938 },
  },
  {
    name: "Vancouver International Airport (YVR)",
    uid: "https://yvr.ca/en",
    address: { locality: "Richmond", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 49.196_687, longitude: -123.181_563 },
  },
  {
    name: "Velencia",
    address: { locality: "Velencia", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 39.466_062, longitude: -0.377_437 },
  },
  {
    name: "Vigo-Guixar",
    address: { locality: "Vigo", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 42.239_312, longitude: -8.712_063 },
  },
  {
    name: "Vigo-Urzáiz",
    address: { locality: "Vigo", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 42.235_312, longitude: -8.710_938 },
  },
  {
    name: "Walsall (WSL)",
    address: { locality: "Walsall", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.584_313, longitude: -1.985_562 },
  },
  {
    name: "Washington Dulles International Airport (IAD)",
    uid: "https://flydulles.com",
    address: { locality: "Dulles", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 38.953_188, longitude: -77.447_812 },
  },
  {
    name: "Wellington",
    address: { locality: "Wellington", countryName: "New Zealand" },
    category: ["station"],
    geo: { latitude: -41.279_187, longitude: 174.780_312 },
  },
  {
    name: "Wellington",
    address: {
      locality: "Wellington Ferry Terminal",
      countryName: "New Zealand",
    },
    category: ["port"],
    geo: { latitude: -41.264_188, longitude: 174.787_063 },
  },
  {
    name: "Wellington International Airport (WLG)",
    uid: "https://wellingtonairport.co.nz",
    address: { locality: "Wellington", countryName: "New Zealand" },
    category: ["airport"],
    geo: { latitude: -41.327_562, longitude: 174.807_563 },
  },
  {
    name: "Wien",
    address: { locality: "Vienna", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.186_667, longitude: 16.38 },
  },
  {
    name: "Winchester (WIN)",
    address: { locality: "Winchester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.067, longitude: -1.32 },
  },
  {
    name: "York (YRK)",
    address: { locality: "York", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.957_937, longitude: -1.093_187 },
  },
  {
    name: "Zürich",
    address: { locality: "Zurich", countryName: "Switzerland" },
    category: ["station"],
    geo: { latitude: 47.377_813, longitude: 8.540_312 },
  },
];
