export const places = [
  {
    name: "Aberdeen (ABD)",
    address: { locality: "Aberdeen", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 57.143687, longitude: -2.098812 },
  },
  {
    name: "Ålesund",
    address: { locality: "Ålesund", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.469563, longitude: 6.152188 },
  },
  {
    name: "Amara Donostia",
    address: { locality: "Donostia-San Sebastián", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 43.313188, longitude: -1.981687 },
  },
  {
    name: "Amsterdam Airport Schiphol (AMS)",
    uid: "https://schiphol.nl",
    address: { locality: "Amsterdam", countryName: "Netherlands" },
    category: ["airport"],
    geo: { latitude: 52.310563, longitude: 4.768313 },
  },
  {
    name: "Amsterdam Amstel",
    address: { locality: "Amsterdam", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 52.346688, longitude: 4.918313 },
  },
  {
    name: "Amsterdam Centraal",
    address: { locality: "Amsterdam", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 52.379188, longitude: 4.900313 },
  },
  {
    name: "Angmering (ANG)",
    address: { locality: "East Preston", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.816389, longitude: -0.489167 },
  },
  {
    name: "Åndalsnes",
    address: { locality: "Åndalsnes", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.567563, longitude: 7.694312 },
  },
  {
    name: "Antwerpen-Centraal",
    address: { locality: "Antwerp", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 51.217187, longitude: 4.421438 },
  },
  {
    name: "Ashford International (AFK)",
    address: { locality: "Ashford", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.143687, longitude: 0.876313 },
  },
  {
    name: "Auckland Airport (AKL)",
    uid: "https://aucklandairport.co.nz",
    address: { locality: "Auckland", countryName: "New Zealand" },
    category: ["airport"],
    geo: { latitude: -37.008187, longitude: 174.785063 },
  },
  {
    name: "Augsburg",
    address: { locality: "Augsburg", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.365556, longitude: 10.886389 },
  },
  {
    name: "Austin-Bergstrom International Airport (AUS)",
    uid: "https://austintexas.gov/airport",
    address: { locality: "Austin", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 30.197438, longitude: -97.666313 },
  },
  {
    name: "Aviemore (AVM)",
    address: { locality: "Aviemore", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 57.1886, longitude: -3.8288 },
  },
  {
    name: "Bahnhof Basel SBB",
    address: { locality: "Basel", countryName: "Switzerland" },
    category: ["station"],
    geo: { latitude: 47.547563, longitude: 7.589688 },
  },
  {
    name: "Barcelona França",
    address: { locality: "Barcelona", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 41.383938, longitude: 2.186438 },
  },
  {
    name: "Barcelona Sants",
    address: { locality: "Barcelona", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 41.378938, longitude: 2.139938 },
  },
  {
    name: "Barnham (BAA)",
    address: { locality: "Barnham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.830938, longitude: -0.640062 },
  },
  {
    name: "Bath Spa (BTH)",
    address: { locality: "Bath", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.377688, longitude: -2.356938 },
  },
  {
    name: "Belfast International Airport (BFS)",
    uid: "https://belfastairport.com",
    address: { locality: "Belfast", countryName: "Northern Ireland" },
    category: ["airport"],
    geo: { latitude: 54.656313, longitude: -6.217187 },
  },
  {
    name: "Belfast Lanyon Place",
    address: { locality: "Belfast", countryName: "Northern Ireland" },
    category: ["station"],
    geo: { latitude: 54.595188, longitude: -5.917187 },
  },
  {
    name: "Berlin",
    address: { locality: "Berlin", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 52.525063, longitude: 13.369438 },
  },
  {
    name: "Berlin Schönefeld Airport (SXF)",
    uid: "https://berlin-airport.de/en",
    address: { locality: "Berlin", countryName: "Germany" },
    category: ["airport"],
    geo: { latitude: 52.373313, longitude: 13.506438 },
  },
  {
    name: "Berwick-upon-Tweed (BWK)",
    address: { locality: "Berwick-upon-Tweed", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.774556, longitude: -2.010542 },
  },
  {
    name: "Birmingham Airport (BHX)",
    uid: "https://birminghamairport.co.uk",
    address: { locality: "Birmingham", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 52.452438, longitude: -1.743562 },
  },
  {
    name: "Birmingham Moor Street (BMO)",
    address: { locality: "Birmingham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.478938, longitude: -1.892562 },
  },
  {
    name: "Birmingham New Street (BHM)",
    address: { locality: "Birmingham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.477812, longitude: -1.898937 },
  },
  {
    name: "Bloxwich North (BWN)",
    address: { locality: "Walsall", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.625313, longitude: -2.017687 },
  },
  {
    name: "Bournemouth (BMH)",
    address: { locality: "Bournemouth", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.728, longitude: -1.864 },
  },
  {
    name: "Brasília–Presidente Juscelino Kubitschek International Airport (BSB)",
    uid: "https://www.bsb.aero/br/",
    address: { locality: "Brasília", countryName: "Brazil" },
    category: ["airport"],
    geo: { latitude: -15.869688, longitude: -47.917187 },
  },
  {
    name: "Brighton (BTN)",
    address: { locality: "Brighton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.828813, longitude: -0.140938 },
  },
  {
    name: "Bristol Temple Meads (BRI)",
    address: { locality: "Bristol", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.449688, longitude: -2.581062 },
  },
  {
    name: "Britomart Transport Centre",
    address: { locality: "Auckland", countryName: "New Zealand" },
    category: ["station"],
    geo: { latitude: -36.844188, longitude: 174.767812 },
  },
  {
    name: "Bruges",
    address: { locality: "Bruges", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 51.197688, longitude: 3.217813 },
  },
  {
    name: "Brussels-South",
    address: { locality: "Brussels", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 50.836063, longitude: 4.335438 },
  },
  {
    name: "Budapest Keleti",
    address: { locality: "Budapest", countryName: "Hungary" },
    category: ["station"],
    geo: { latitude: 47.500438, longitude: 19.083938 },
  },
  {
    name: "Cabis Bay (CBB)",
    address: { locality: "St Ives", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.197063, longitude: -5.464062 },
  },
  {
    name: "Caesars Palace Hotel & Casino",
    address: { locality: "Las Vegas", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 36.116173, longitude: -115.17669 },
  },
  {
    name: "Cairns International Airport (CNS)",
    uid: "https://cairnsairport.com.au",
    address: { locality: "Cairns", countryName: "Australia" },
    category: ["airport"],
    geo: { latitude: -16.877813, longitude: 145.749937 },
  },
  {
    name: "Cambridge (CBG)",
    address: { locality: "Cambridge", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.194187, longitude: 0.137438 },
  },
  {
    name: "Cannock (CAO)",
    address: { locality: "Cannock", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.686, longitude: -2.022 },
  },
  {
    name: "Cardiff Central (CDF)",
    address: { locality: "Cardiff", countryName: "Wales" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.476188, longitude: -3.179062 },
  },
  {
    name: "Carlisle (CAR)",
    address: { locality: "Carlisle", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 54.890688, longitude: -2.933188 },
  },
  {
    name: "Chambéry–Challes-les-Eaux",
    address: { locality: "Chambéry", countryName: "France" },
    category: ["station"],
    geo: { latitude: 45.571389, longitude: 5.919444 },
  },
  {
    name: "Chester (CTR)",
    address: { locality: "Chester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.196562, longitude: -2.880187 },
  },
  {
    name: "Chicago Midway International Airport (MDW)",
    uid: "https://flychicago.com/midway",
    address: { locality: "Chicago", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 41.786812, longitude: -87.752188 },
  },
  {
    name: "Chorley (CRL)",
    address: { locality: "Chorley", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.652563, longitude: -2.626937 },
  },
  {
    name: "Clapham Junction (CLJ)",
    address: { locality: "Clapham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.465187, longitude: -0.170812 },
  },
  {
    name: "Como San Giovanni",
    address: { locality: "Como", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.808889, longitude: 9.072306 },
  },
  {
    name: "Copenhagen Airport, Kastrup (CPH)",
    uid: "https://cph.dk/en",
    address: { locality: "Kastrup", countryName: "Denmark" },
    category: ["airport"],
    geo: { latitude: 55.618063, longitude: 12.650813 },
  },
  {
    name: "Copenhagen Central",
    address: { locality: "Copenhagen", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 55.672813, longitude: 12.564938 },
  },
  {
    name: "Coventry (COV)",
    address: { locality: "Coventry", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.401, longitude: -1.5136 },
  },
  {
    name: "Craignure Mull Ferry Terminal",
    address: { locality: "Craignure", countryName: "Scotland" },
    category: ["port"],
    geo: { latitude: 56.470688, longitude: -5.706312 },
  },
  {
    name: "Crewe (CRE)",
    address: { locality: "Crewe", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.089563, longitude: -2.433562 },
  },
  {
    name: "Dallas/Fort Worth International Airport (DFW)",
    uid: "https://dfwairport.com",
    address: { locality: "Dallas", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 32.899812, longitude: -97.040312 },
  },
  {
    name: "Den Haag Centraal",
    address: { locality: "The Hague", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 52.080563, longitude: 4.325813 },
  },
  {
    name: "Derby (DBY)",
    address: { locality: "Derby", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.916188, longitude: -1.463313 },
  },
  {
    name: "Dieppe",
    address: { locality: "Dieppe", countryName: "France" },
    category: ["station"],
    geo: { latitude: 49.921438, longitude: 1.081063 },
  },
  {
    name: "Doncaster (DON)",
    address: { locality: "Doncaster", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.5225, longitude: -1.1395 },
  },
  {
    name: "Düsseldorf",
    address: { locality: "Düsseldorf", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 51.220278, longitude: 6.792778 },
  },
  {
    name: "Dubai International Airport (DXB)",
    uid: "https://dubaiairports.ae",
    address: { locality: "Dubai", countryName: "United Arab Emirates" },
    category: ["airport"],
    geo: { latitude: 25.253187, longitude: 55.365688 },
  },
  {
    name: "Dublin Airport (DUB)",
    uid: "https://dublinairport.com",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["airport"],
    geo: { latitude: 53.426438, longitude: -6.249937 },
  },
  {
    name: "Dublin Connolly",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["station"],
    geo: { latitude: 53.350938, longitude: -6.249937 },
  },
  {
    name: "Dublin Heuston",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["station"],
    geo: { latitude: 53.346313, longitude: -6.294187 },
  },
  {
    name: "Dublin Port",
    uid: "https://dublinport.ie",
    address: { locality: "Dublin", countryName: "Ireland" },
    category: ["port"],
    geo: { latitude: 53.345063, longitude: -6.196187 },
  },
  {
    name: "Dundee (DEE)",
    address: { locality: "Dundee", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.457687, longitude: -2.969437 },
  },
  {
    name: "Durham (DHM)",
    address: { locality: "Durham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 54.779749, longitude: -1.581512 },
  },
  {
    name: "Edinburgh Waverley (EDB)",
    address: { locality: "Edinburgh", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.951938, longitude: -3.189937 },
  },
  {
    name: "Emeryville",
    address: { locality: "Emeryville", countryName: "United States" },
    category: ["station"],
    geo: { latitude: 37.840438, longitude: -122.291812 },
  },
  {
    name: "Exeter St David’s (EXD)",
    address: { locality: "Exeter", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.729312, longitude: -3.543563 },
  },
  {
    name: "Fareham (FRM)",
    address: { locality: "Fareham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.852934, longitude: -1.191898 },
  },
  {
    name: "Farringdon (ZFD)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.520556, longitude: -0.105 },
  },
  {
    name: "Florence Santa Maria Novella",
    address: { locality: "Florence", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 43.776438, longitude: 11.247813 },
  },
  {
    name: "Flåm",
    address: { locality: "Flåm", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 60.863687, longitude: 7.118938 },
  },
  {
    name: "Frankfurt Airport (FRA)",
    uid: "https://frankfurt-airport.com",
    address: { locality: "Frankfurt am Main", countryName: "Germany" },
    category: ["airport"],
    geo: { latitude: 50.037937, longitude: 8.562188 },
  },
  {
    name: "Frankfurt (Main)",
    address: { locality: "Frankfurt am Main", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 50.106944, longitude: 8.6625 },
  },
  {
    name: "Fredericia",
    address: { locality: "Fredericia", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 55.568188, longitude: 9.740437 },
  },
  {
    name: "Freiburg",
    address: { locality: "Freiburg im Breisgau", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 47.996562, longitude: 7.840438 },
  },
  {
    name: "Füssen",
    address: { locality: "Füssen", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 47.570263, longitude: 10.697818 },
  },
  {
    name: "Galway",
    address: { locality: "Galway", countryName: "Ireland" },
    category: ["station"],
    geo: { latitude: 53.273563, longitude: -9.047063 },
  },
  {
    name: "Gatwick (GTW)",
    address: { locality: "Gatwick", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.156688, longitude: -0.161187 },
  },
  {
    name: "Gatwick Airport (LGW)",
    uid: "https://gatwickairport.com",
    address: { locality: "Gatwick", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 51.153688, longitude: -0.182062 },
  },
  {
    name: "Geiranger",
    address: { locality: "Geiranger", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.102188, longitude: 7.204813 },
  },
  {
    name: "Glasgow Central (GLC)",
    address: { locality: "Glasgow", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.859062, longitude: -4.258062 },
  },
  {
    name: "Glasgow Queen Street (GLQ)",
    address: { locality: "Glasgow", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 55.862437, longitude: -4.251187 },
  },
  {
    name: "Gothenburg Central",
    address: { locality: "Gothenburg", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 57.708562, longitude: 11.973313 },
  },
  {
    name: "Greenwich (GNW)",
    address: { locality: "Greenwich", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.478062, longitude: -0.013188 },
  },
  {
    name: "Guernsey Ferry Port",
    address: { locality: "St. Peter Port", countryName: "Guernsey" },
    category: ["port"],
    geo: { latitude: 49.457313, longitude: -2.529062 },
  },
  {
    name: "Hamburg",
    address: { locality: "Hamburg", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 53.552938, longitude: 10.006563 },
  },
  {
    name: "Hartsfield-Jackson Atlanta International Airport (ATL)",
    uid: "https://atl.com",
    address: { locality: "Atlanta", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 33.640687, longitude: -84.427688 },
  },
  {
    name: "Harwich International (HPQ)",
    address: { locality: "Harwich", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.947, longitude: 1.255 },
  },
  {
    name: "Harwich International Port",
    address: { locality: "Harwich", countryName: "England" },
    category: ["port"],
    geo: { latitude: 51.948, longitude: 1.255 },
  },
  {
    name: "Hässleholm Central",
    address: { locality: "Hässleholm", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 56.157813, longitude: 13.763188 },
  },
  {
    name: "Hastings (HGS)",
    address: { locality: "Hastings", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.857937, longitude: 0.576813 },
  },
  {
    name: "Haugesund",
    address: { locality: "Haugesund", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 59.411063, longitude: 5.257313 },
  },
  {
    name: "Havant (HAV)",
    address: { locality: "Havant", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.854312, longitude: -0.981562 },
  },
  {
    name: "Hellesylt",
    address: { locality: "Hellesylt", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 62.085563, longitude: 6.873938 },
  },
  {
    name: "Hendaye",
    address: { locality: "Hendaye", countryName: "France" },
    category: ["station"],
    geo: { latitude: 43.353062, longitude: -1.781812 },
  },
  {
    name: "Hilton Santa Monica Hotel & Suites",
    address: { locality: "Santa Monica", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 34.01173, longitude: -118.49117 },
  },
  {
    name: "Hoek van Holland Haven",
    address: { locality: "Hoek van Holland", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 51.981111, longitude: 4.128611 },
  },
  {
    name: "Holiday Inn Express & Suites Albuquerque Historic Old Town",
    address: { locality: "Albuquerque", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 35.10866, longitude: -106.66046 },
  },
  {
    name: "Holyhead (HHD)",
    address: { locality: "Holyhead", countryName: "Wales" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.307688, longitude: -4.631062 },
  },
  {
    name: "Hove (HOV)",
    address: { locality: "Hove", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.835063, longitude: -0.171062 },
  },
  {
    name: "Hyatt Regency",
    address: { locality: "Austin", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 30.26057, longitude: -97.74721 },
  },
  {
    name: "Innsbruck",
    address: { locality: "Innsbruck", countryName: "Austria" },
    category: ["station"],
    geo: { latitude: 47.263313, longitude: 11.400938 },
  },
  {
    name: "Inverness (INV)",
    address: { locality: "Inverness", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 57.48, longitude: -4.223 },
  },
  {
    name: "John F. Kennedy International Airport (JFK)",
    uid: "https://jfkairport.com",
    address: { locality: "New York", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 40.641312, longitude: -73.778188 },
  },
  {
    name: "Keflavík International Airport (KEF)",
    uid: "https://www.isavia.is/en/keflavik-airport",
    address: { locality: "Keflavík", countryName: "Iceland" },
    category: ["airport"],
    geo: { latitude: 63.978563, longitude: -22.635063 },
  },
  {
    name: "King Street Station",
    address: { locality: "Seattle", countryName: "United States" },
    category: ["station"],
    geo: { latitude: 47.598438, longitude: -122.329937 },
  },
  {
    name: "Köln",
    address: { locality: "Cologne", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 50.943188, longitude: 6.958562 },
  },
  {
    name: "Le Havre",
    address: { locality: "Le Harve", countryName: "France" },
    category: ["station"],
    geo: { latitude: 49.492687, longitude: 0.124813 },
  },
  {
    name: "Leeds (LDS)",
    address: { locality: "Leeds", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.794, longitude: -1.547 },
  },
  {
    name: "Leicester (LEI)",
    address: { locality: "Leicester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.631188, longitude: -1.125187 },
  },
  {
    name: "Lewes (LWS)",
    address: { locality: "Lewes", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.870563, longitude: 0.011437 },
  },
  {
    name: "Lille-Europe",
    address: { locality: "Lille", countryName: "France" },
    category: ["station"],
    geo: { latitude: 50.639062, longitude: 3.075688 },
  },
  {
    name: "Lisbon Orient",
    address: { locality: "Lisbon", countryName: "Portugal" },
    category: ["station"],
    geo: { latitude: 38.767813, longitude: -9.099312 },
  },
  {
    name: "Lisbon Portela Airport (LIS)",
    uid: "https://www.ana.pt/en/lis/home",
    address: { locality: "Lisbon", countryName: "Portugal" },
    category: ["airport"],
    geo: { latitude: 38.775563, longitude: -9.135312 },
  },
  {
    name: "Littlehampton (LIT)",
    address: { locality: "Littlehampton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.810063, longitude: -0.545938 },
  },
  {
    name: "Liverpool Lime Street (LIV)",
    address: { locality: "Liverpool", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.407563, longitude: -2.977312 },
  },
  {
    name: "Liège-Guillemins",
    address: { locality: "Liège", countryName: "Belgium" },
    category: ["station"],
    geo: { latitude: 50.624438, longitude: 5.566688 },
  },
  {
    name: "London Blackfriars (BFR)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.5116, longitude: -0.103 },
  },
  {
    name: "London Bridge (LBG)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.504312, longitude: -0.084812 },
  },
  {
    name: "London Euston (EUS)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.528063, longitude: -0.133188 },
  },
  {
    name: "London Heathrow Airport (LHR)",
    uid: "https://heathrow.com",
    address: { locality: "London", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 51.470063, longitude: -0.454312 },
  },
  {
    name: "London King’s Cross (KGX)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.532063, longitude: -0.123312 },
  },
  {
    name: "London Liverpool Street (LST)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.5186, longitude: -0.0813 },
  },
  {
    name: "London Luton Airport (LTN)",
    uid: "https://www.london-luton.co.uk",
    address: { locality: "Luton", countryName: "England" },
    category: ["airport"],
    geo: { latitude: 51.876313, longitude: -0.371687 },
  },
  {
    name: "London Marylebone (MYB)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.522438, longitude: -0.163187 },
  },
  {
    name: "London Paddington (PAD)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.516687, longitude: -0.176937 },
  },
  {
    name: "London St Pancras International (STP)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.531438, longitude: -0.126187 },
  },
  {
    name: "London Victoria (VIC)",
    address: { locality: "London", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.495187, longitude: -0.143937 },
  },
  {
    name: "Los Angeles International Airport (LAX)",
    uid: "https://flylax.com",
    address: { locality: "Los Angeles", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 33.941563, longitude: -118.408563 },
  },
  {
    name: "Lucerne",
    address: { locality: "Lucerne", countryName: "Switzerland" },
    category: ["station"],
    geo: { latitude: 47.050438, longitude: 8.310313 },
  },
  {
    name: "Luton (LUT)",
    address: { locality: "Luton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.88227, longitude: -0.41432 },
  },
  {
    name: "Lyon-Part-Dieu",
    address: { locality: "Lyon", countryName: "France" },
    category: ["station"],
    geo: { latitude: 45.760556, longitude: 4.859444 },
  },
  {
    name: "Maastricht",
    address: { locality: "Maastricht", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 50.849688, longitude: 5.705312 },
  },
  {
    name: "Madrid Atocha",
    address: { locality: "Madrid", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 40.405063, longitude: -3.688312 },
  },
  {
    name: "Madrid Chamartín",
    address: { locality: "Madrid", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 40.471938, longitude: -3.682562 },
  },
  {
    name: "Malmö Central",
    address: { locality: "Malmö", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 55.609062, longitude: 12.999938 },
  },
  {
    name: "Manchester Piccadilly (MAN)",
    address: { locality: "Manchester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.477438, longitude: -2.231187 },
  },
  {
    name: "Manchester Victoria (MCV)",
    address: { locality: "Manchester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.487562, longitude: -2.242188 },
  },
  {
    name: "Margate (MAR)",
    address: { locality: "Margate", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.385437, longitude: 1.372313 },
  },
  {
    name: "McCarran International Airport (LAS)",
    uid: "https://mccarran.com",
    address: { locality: "Las Vegas", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 36.083937, longitude: -115.153688 },
  },
  {
    name: "Melbourne Airport (MEL)",
    uid: "https://www.melbourneairport.com.au",
    address: { locality: "Melbourne", countryName: "Australia" },
    category: ["airport"],
    geo: { latitude: -37.669063, longitude: 144.841063 },
  },
  {
    name: "Milano Centrale",
    address: { locality: "Milan", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.486111, longitude: 9.203611 },
  },
  {
    name: "Milton Keynes Central (MKC)",
    address: { locality: "Milton Keynes", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.034438, longitude: -0.773812 },
  },
  {
    name: "Montréal–Trudeau International Airport (YUL)",
    uid: "https://admtl.com",
    address: { locality: "Montréal", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 45.465688, longitude: -73.745438 },
  },
  {
    name: "Munich International Airport (MUC)",
    uid: "https://munich-airport.com",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["airport"],
    geo: { latitude: 48.353688, longitude: 11.775063 },
  },
  {
    name: "Munich",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.140833, longitude: 11.555 },
  },
  {
    name: "Munich East",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.126944, longitude: 11.604722 },
  },
  {
    name: "Munich Pasing",
    address: { locality: "Munich", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.150063, longitude: 11.461562 },
  },
  {
    name: "Newark Liberty International Airport (EWR)",
    uid: "https://newarkairport.com",
    address: { locality: "Newark", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 40.689563, longitude: -74.174437 },
  },
  {
    name: "Newark Northgate (NNG)",
    address: { locality: "Newark-on-Trent", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.081, longitude: -0.799 },
  },
  {
    name: "Newcastle (NCL)",
    address: { locality: "Newcastle", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 54.968438, longitude: -1.617063 },
  },
  {
    name: "Newhaven Harbour (NVH)",
    address: { locality: "Newhaven", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.789688, longitude: 0.055313 },
  },
  {
    name: "Newport (NWP)",
    address: { locality: "Newport", countryName: "Wales" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.588688, longitude: -3.001187 },
  },
  {
    name: "Newquay (NQY)",
    address: { locality: "Newquay", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.415063, longitude: -5.075687 },
  },
  {
    name: "Nice-Ville",
    address: { locality: "Nice", countryName: "France" },
    category: ["station"],
    geo: { latitude: 43.704312, longitude: 7.261938 },
  },
  {
    name: "Norman Y. Mineta San Jose International Airport (SJC)",
    uid: "https://flysanjose.com",
    address: { locality: "San Jose", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 37.363937, longitude: -121.928938 },
  },
  {
    name: "Norwich (NRW)",
    address: { locality: "Norwich", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.626938, longitude: 1.306563 },
  },
  {
    name: "Nottingham (NOT)",
    address: { locality: "Nottingham", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.947063, longitude: -1.146812 },
  },
  {
    name: "Nürnberg",
    address: { locality: "Nürnberg", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 49.446389, longitude: 11.081944 },
  },
  {
    name: "Oban (OBN)",
    address: { locality: "Oban", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.412563, longitude: -5.473937 },
  },
  {
    name: "Oban Ferry Terminal",
    address: { locality: "Oban", countryName: "Scotland" },
    category: ["port"],
    geo: { latitude: 56.412188, longitude: -5.476062 },
  },
  {
    name: "Olden",
    address: { locality: "Olden", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 61.842688, longitude: 6.810688 },
  },
  {
    name: "Oslo Central",
    address: { locality: "Oslo", countryName: "Norway" },
    category: ["station"],
    geo: { latitude: 59.911063, longitude: 10.752438 },
  },
  {
    name: "Ottawa International Airport (YOW)",
    uid: "https://yow.ca/en",
    address: { locality: "Ottawa", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 45.319188, longitude: -75.669188 },
  },
  {
    name: "Ottawa Train Station",
    address: { locality: "Ottawa", countryName: "Canada" },
    category: ["station"],
    geo: { latitude: 45.416438, longitude: -75.651688 },
  },
  {
    name: "O’Hare International Airport (ORD)",
    uid: "https://flychicago.com/ohare",
    address: { locality: "Chicago", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 41.974187, longitude: -87.907313 },
  },
  {
    name: "Oulx–Cesana–Claviere–Sestriere",
    address: { locality: "Oulx", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.038611, longitude: 6.831389 },
  },
  {
    name: "Pacific Central Station",
    address: { locality: "Vancouver", countryName: "Canada" },
    category: ["station"],
    geo: { latitude: 49.273688, longitude: -123.097938 },
  },
  {
    name: "Par (PAR)",
    address: { locality: "Par", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.355938, longitude: -4.704438 },
  },
  {
    name: "Paris-Austerlitz",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.841813, longitude: 2.366062 },
  },
  {
    name: "Paris-Est",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.876812, longitude: 2.359312 },
  },
  {
    name: "Paris-Gare-de-Lyon",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.844313, longitude: 2.374438 },
  },
  {
    name: "Paris-Montparnasse",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.841188, longitude: 2.320563 },
  },
  {
    name: "Paris-Nord",
    address: { locality: "Paris", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.880938, longitude: 2.355312 },
  },
  {
    name: "Penzance (PNZ)",
    address: { locality: "Penzance", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.121688, longitude: -5.532563 },
  },
  {
    name: "Perth (PTH)",
    address: { locality: "Perth", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.3916, longitude: -3.4384 },
  },
  {
    name: "Petersfield (PTR)",
    address: { locality: "Petersfield", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.007, longitude: -0.941 },
  },
  {
    name: "Phoenix Sky Harbor International Airport (PHX)",
    uid: "https://skyharbor.com",
    address: { locality: "Phoenix", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 33.437313, longitude: -112.007812 },
  },
  {
    name: "Picton",
    address: { locality: "Picton Ferry Terminal", countryName: "New Zealand" },
    category: ["port"],
    geo: { latitude: -41.285312, longitude: 174.005313 },
  },
  {
    name: "Poole Ferry Terminal",
    address: { locality: "Poole", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.708062, longitude: -1.995437 },
  },
  {
    name: "Port of Dieppe",
    address: { locality: "Dieppe", countryName: "France" },
    category: ["port"],
    geo: { latitude: 49.933688, longitude: 1.088063 },
  },
  {
    name: "Port of Holyhead",
    uid: "https://holyheadport.co.uk",
    address: { locality: "Holyhead", countryName: "Wales" },
    category: ["port"],
    geo: { latitude: 53.309313, longitude: -4.628937 },
  },
  {
    name: "Port of Newhaven",
    uid: "https://newhavenport.com",
    address: { locality: "Newhaven", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.790312, longitude: 0.054688 },
  },
  {
    name: "Port of Strevanger",
    address: { locality: "Strevanger", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 58.972563, longitude: 5.729813 },
  },
  {
    name: "Portland International Airport (PDX)",
    uid: "https://flypdx.com",
    address: { locality: "Portland", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 45.591313, longitude: -122.592313 },
  },
  {
    name: "Porto (OPO)",
    address: { locality: "Porto", countryName: "Portugal" },
    category: ["airport"],
    geo: { latitude: 41.235556, longitude: -8.678056 },
  },
  {
    name: "Porto Campanha",
    address: { locality: "Porto", countryName: "Portugal" },
    category: ["station"],
    geo: { latitude: 41.148813, longitude: -8.585437 },
  },
  {
    name: "Portsmouth Harbour (PMH)",
    address: { locality: "Portsmouth", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.797188, longitude: -1.107563 },
  },
  {
    name: "Portsmouth Harbour Station Pier",
    address: { locality: "Portsmouth", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.797063, longitude: -1.109312 },
  },
  {
    name: "Prague",
    address: { locality: "Prague", countryName: "Czechia" },
    category: ["station"],
    geo: { latitude: 50.083188, longitude: 14.435313 },
  },
  {
    name: "Preston (PRE)",
    address: { locality: "Preston", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.755313, longitude: -2.707188 },
  },
  {
    name: "Preston Park (PRP)",
    address: { locality: "Brighton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.845938, longitude: -0.155062 },
  },
  {
    name: "Puttgarden",
    address: { locality: "Puttgarden", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 54.500938, longitude: 11.226188 },
  },
  {
    name: "Puttgarden",
    address: { locality: "Puttgarden", countryName: "Germany" },
    category: ["port"],
    geo: { latitude: 54.502813, longitude: 11.228688 },
  },
  {
    name: "Reading (RDG)",
    address: { locality: "Reading", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.458313, longitude: -0.971437 },
  },
  {
    name: "Roma Termini",
    address: { locality: "Rome", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 41.901063, longitude: 12.501188 },
  },
  {
    name: "Rome Ciampino Giovan Battista Pastine Airport (CIA)",
    uid: "https://adr.it/ciampino",
    address: { locality: "Rome", countryName: "Italy" },
    category: ["airport"],
    geo: { latitude: 41.799188, longitude: 12.592813 },
  },
  {
    name: "Rotterdam Centraal",
    address: { locality: "Rotterdam", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 51.924313, longitude: 4.470063 },
  },
  {
    name: "Rouen-Rive-Droite",
    address: { locality: "Rouen", countryName: "France" },
    category: ["station"],
    geo: { latitude: 49.448813, longitude: 1.094188 },
  },
  {
    name: "Ryde Pier Head (RYP)",
    address: { locality: "Ryde", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.739187, longitude: -1.160062 },
  },
  {
    name: "Ryde Pier Head",
    address: { locality: "Ryde", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.739438, longitude: -1.160562 },
  },
  {
    name: "Rødby Færge",
    address: { locality: "Rødby", countryName: "Denmark" },
    category: ["station"],
    geo: { latitude: 54.655188, longitude: 11.354813 },
  },
  {
    name: "Rødbyhavn",
    address: { locality: "Rødby", countryName: "Denmark" },
    category: ["port"],
    geo: { latitude: 54.654688, longitude: 11.351438 },
  },
  {
    name: "San Francisco International Airport (SFO)",
    uid: "https://flysfo.com",
    address: { locality: "San Francisco", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 37.621312, longitude: -122.378938 },
  },
  {
    name: "San Sebastián",
    address: { locality: "Donostia-San Sebastián", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 43.316188, longitude: -1.977437 },
  },
  {
    name: "Seattle-Tacoma International Airport (SEA)",
    uid: "https://flysea.org",
    address: { locality: "SeaTac", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 47.450187, longitude: -122.308813 },
  },
  {
    name: "Shanklin (SHN)",
    address: { locality: "Shanklin", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.633813, longitude: -1.179937 },
  },
  {
    name: "Sheffield (SHF)",
    address: { locality: "Sheffield", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.378313, longitude: -1.462937 },
  },
  {
    name: "Sitges",
    address: { locality: "Sitges", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 41.239075, longitude: 1.809672 },
  },
  {
    name: "Southampton Airport Parkway (SOA)",
    address: { locality: "Southampton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.950813, longitude: -1.363062 },
  },
  {
    name: "Southampton Central (SOU)",
    address: { locality: "Southampton", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.908, longitude: -1.414 },
  },
  {
    name: "Southampton Cruise Terminal",
    uid: "https://southamptonvts.co.uk",
    address: { locality: "Southampton", countryName: "England" },
    category: ["port"],
    geo: { latitude: 50.893563, longitude: -1.400062 },
  },
  {
    name: "St Erth (SER)",
    address: { locality: "St Erth", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.170563, longitude: -5.444312 },
  },
  {
    name: "St Ives (SIV)",
    address: { locality: "St Ives", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.208937, longitude: -5.477937 },
  },
  {
    name: "Stirling (STG)",
    address: { locality: "Stirling", countryName: "Scotland" },
    category: ["national_rail", "station"],
    geo: { latitude: 56.119813, longitude: -3.935437 },
  },
  {
    name: "Stockholm Central",
    address: { locality: "Stockholm", countryName: "Sweden" },
    category: ["station"],
    geo: { latitude: 59.330063, longitude: 18.058313 },
  },
  {
    name: "Strasbourg-Ville",
    address: { locality: "Strasbourg", countryName: "France" },
    category: ["station"],
    geo: { latitude: 48.585063, longitude: 7.734438 },
  },
  {
    name: "Stuttgart",
    address: { locality: "Stuttgart", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.783889, longitude: 9.181667 },
  },
  {
    name: "Suvarnabhumi Airport (BKK)",
    uid: "https://suvarnabhumi.airportthai.co.th",
    address: { locality: "Bang Phli", countryName: "Thailand" },
    category: ["airport"],
    geo: { latitude: 13.689937, longitude: 100.750063 },
  },
  {
    name: "Sydney Airport (SYD)",
    uid: "https://sydneyairport.com.au",
    address: { locality: "Sydney", countryName: "Australia" },
    category: ["airport"],
    geo: { latitude: -33.939938, longitude: 151.175312 },
  },
  {
    name: "São Paulo-Guarulhos International Airport (GRU)",
    uid: "https://www.gru.com.br/en",
    address: { locality: "Guarulhos", countryName: "Brazil" },
    category: ["airport"],
    geo: { latitude: -23.430563, longitude: -46.473062 },
  },
  {
    name: "The Mosser",
    address: { locality: "San Francisco", countryName: "United States" },
    category: ["hotel"],
    geo: { latitude: 37.785084, longitude: -122.405006 },
  },
  {
    name: "Three Bridges (TBD)",
    address: { locality: "Three Bridges", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.118063, longitude: -0.161687 },
  },
  {
    name: "Torino Porta Susa",
    address: { locality: "Turin", countryName: "Italy" },
    category: ["station"],
    geo: { latitude: 45.0725, longitude: 7.665833 },
  },
  {
    name: "Toronto Pearson International Airport (YYZ)",
    uid: "https://torontopearson.com/en",
    address: { locality: "Toronto", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 43.677688, longitude: -79.624813 },
  },
  {
    name: "Toronto Union Station",
    address: { locality: "Toronto", countryName: "Canada" },
    category: ["station"],
    geo: { latitude: 43.645187, longitude: -79.380688 },
  },
  {
    name: "Trondheim",
    address: { locality: "Trondheim", countryName: "Norway" },
    category: ["port"],
    geo: { latitude: 63.438313, longitude: 10.397063 },
  },
  {
    name: "Truro (TRU)",
    address: { locality: "Truro", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 50.264062, longitude: -5.064187 },
  },
  {
    name: "Union Station",
    address: { locality: "Chicago", countryName: "United States" },
    category: ["station"],
    geo: { latitude: 41.878688, longitude: -87.640438 },
  },
  {
    name: "Utrecht Centraal",
    address: { locality: "Utrecht", countryName: "Netherlands" },
    category: ["station"],
    geo: { latitude: 52.089438, longitude: 5.109938 },
  },
  {
    name: "Vancouver International Airport (YVR)",
    uid: "https://yvr.ca/en",
    address: { locality: "Richmond", countryName: "Canada" },
    category: ["airport"],
    geo: { latitude: 49.196687, longitude: -123.181563 },
  },
  {
    name: "Velencia",
    address: { locality: "Velencia", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 39.466062, longitude: -0.377437 },
  },
  {
    name: "Vigo-Guixar",
    address: { locality: "Vigo", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 42.239312, longitude: -8.712063 },
  },
  {
    name: "Vigo-Urzáiz",
    address: { locality: "Vigo", countryName: "Spain" },
    category: ["station"],
    geo: { latitude: 42.235312, longitude: -8.710938 },
  },
  {
    name: "Walsall (WSL)",
    address: { locality: "Walsall", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 52.584313, longitude: -1.985562 },
  },
  {
    name: "Washington Dulles International Airport (IAD)",
    uid: "https://flydulles.com",
    address: { locality: "Dulles", countryName: "United States" },
    category: ["airport"],
    geo: { latitude: 38.953188, longitude: -77.447812 },
  },
  {
    name: "Wellington",
    address: { locality: "Wellington", countryName: "New Zealand" },
    category: ["station"],
    geo: { latitude: -41.279187, longitude: 174.780312 },
  },
  {
    name: "Wellington",
    address: {
      locality: "Wellington Ferry Terminal",
      countryName: "New Zealand",
    },
    category: ["port"],
    geo: { latitude: -41.264188, longitude: 174.787063 },
  },
  {
    name: "Wellington International Airport (WLG)",
    uid: "https://wellingtonairport.co.nz",
    address: { locality: "Wellington", countryName: "New Zealand" },
    category: ["airport"],
    geo: { latitude: -41.327562, longitude: 174.807563 },
  },
  {
    name: "Wien",
    address: { locality: "Vienna", countryName: "Germany" },
    category: ["station"],
    geo: { latitude: 48.186667, longitude: 16.38 },
  },
  {
    name: "Winchester (WIN)",
    address: { locality: "Winchester", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 51.067, longitude: -1.32 },
  },
  {
    name: "York (YRK)",
    address: { locality: "York", countryName: "England" },
    category: ["national_rail", "station"],
    geo: { latitude: 53.957937, longitude: -1.093187 },
  },
  {
    name: "Zürich",
    address: { locality: "Zurich", countryName: "Switzerland" },
    category: ["station"],
    geo: { latitude: 47.377813, longitude: 8.540312 },
  },
];
