import { short, long, under } from "./utils/post-path.js";

export const postTypes = {
  article: {
    listPath: "/articles/",
    listSize: 24,
    path: long,
    prefix: "a",
    syndicate: true,
  },
  bookmark: {
    listPath: "/bookmarks/",
    listSize: 24,
    path: long,
    prefix: "b",
    syndicate: true,
  },
  collection: {
    listPath: "/collections/",
    listSize: 24,
    path: under("collections"),
    visibility: "unlisted",
  },
  comments: {
    path: long,
    prefix: "c",
    vocabulary: "feed",
    visibility: "unlisted",
  },
  drawing: {
    listPath: "/drawings/",
    listSize: 24,
    path: short,
    prefix: "d",
    syndicate: true,
  },
  event: {
    listPath: "/events/",
    listSize: 48,
    path: long,
    prefix: "e",
    vocabulary: "event",
  },
  itinerary: {
    listPath: "/travel/",
    listSize: 48,
    path: long,
    prefix: "i",
    vocabulary: "event",
  },
  jam: {
    listPath: "/jams/",
    listSize: 36,
    path: short,
    prefix: "j",
    syndicate: true,
  },
  note: {
    listPath: "/notes/",
    listSize: 36,
    path: short,
    prefix: "n",
    syndicate: true,
  },
  photo: {
    listPath: "/photos/",
    listSize: 36,
    path: short,
    prefix: "p",
    syndicate: true,
  },
  presentation: {
    listPath: "/presentations/",
    path: long,
    prefix: "s",
    syndicate: true,
  },
  project: {
    listPath: "/projects/",
    listSize: 3,
    path: under("projects"),
    prefix: "w",
    syndicate: true,
  },
  reply: {
    listPath: "/replies/",
    listSize: 36,
    path: short,
    prefix: "r",
    syndicate: true,
    visibility: "unlisted",
  },
  trip: {
    listPath: "/trips/",
    path: short,
    prefix: "t",
    vocabulary: "event",
    visibility: "unlisted",
  },
};
