module.exports = {
  article: require('./article.js'),
  attended: require('./attended.js'),
  attending: require('./attending.js'),
  bookmark: require('./bookmark.js'),
  category: require('./category.js'),
  collection: require('./collection.js'),
  comments: require('./comments.js'),
  itinerary: require('./itinerary.js'),
  note: require('./note.js'),
  photo: require('./photo.js'),
  presentation: require('./presentation.js'),
  presented: require('./presented.js'),
  project: require('./project.js'),
  public: require('./public.js'),
  publication: require('./publication.js'),
  reply: require('./reply.js'),
  syndicate: require('./syndicate.js'),
  trip: require('./trip.js'),
};
